on:
  push:
    branches:
      - master
      - main
  pull_request:

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_TAG: user/app:test
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.TEST_TAG }}
          file: Dockerfile
          load: true
          context: .

      - name: Run container
        run: |
          docker run --rm ${{ env.TEST_TAG }} && sleep 5
