on:
  push:
    branches:
      - master
      - main
  pull_request:

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        uses: docker/build-push-action@v5
        with:
          cache-from: type=local,src=${{ env.DOCKER_CACHE}}
          cache-to: type=local,dest=${{ env.DOCKER_CACHE}},mode=max
          tags: ${{ env.TEST_TAG }}
          file: Dockerfile
          load: true
          context: .

      - name: Run container
        run: |
          docker run --rm ${{ env.TEST_TAG }} && sleep 5
