on:
  push:
    branches:
      - master
      - main
  pull_request:

name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Print environment
        run: |
          node --version
          npm --version

      - name: Install Node dependencies
        run: npm ci

      - name: Code Style
        run: npm run cs-check

      - name: Code Lint
        run: npm run lint

      - name: Ext Lint
        run: npx web-ext lint --ignore-files="**/*.min.js" --warnings-as-errors --privileged --self-hosted --source-dir=extension/

  test:
    runs-on: ubuntu-latest
    env:
      TEST_TAG: user/app:test
    steps:
      - uses: actions/checkout@v5

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.TEST_TAG }}
          file: Dockerfile
          load: true
          context: .

      - name: Run container
        run: |
          docker run --rm ${{ env.TEST_TAG }} && sleep 5
